# For Pi Zero W with 32-bit OS (ARMv6)
[target.arm-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"

# For Pi Zero W/2 with 64-bit OS (AArch64)
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
